[package]
name = "patscan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
patscan-rs = { path = "../lib"}
widestring = "1.0.2"